sonar.projectKey=HAMZAMSABRI2_library
sonar.organization=hamzamsabri2
sonar.projectName=BiblioApp

# Sources
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/vendor/**,**/node_modules/**,**/var/**,**/dist/**,**/__tests__/**

# Tests
sonar.tests=backend/tests,frontend/src/__tests__
sonar.test.inclusions=backend/tests/**/*.php,frontend/src/__tests__/**/*.jsx,frontend/src/__tests__/**/*.tsx

# Coverage
sonar.php.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Language settings
sonar.sourceEncoding=UTF-8
sonar.php.version=8.2
